---
Name: MyPwnConfig
after:
  - HaveIBeenPwnedConfig
---
Firesphere\HaveIBeenPwned\Services\HaveIBeenPwnedService:
  allow_pwnd: false
  save_pwnd: false
SilverStripe\Security\Member:
  lock_out_after_incorrect_logins: 30
---
Only:
  environment: dev
---
Firesphere\HaveIBeenPwned\Services\HaveIBeenPwnedService:
  allow_pwnd: true
